language: cpp
git:
  submodules: true
addons:
  apt:
    packages:
    - python
    - python-pip
    - git
    - wget
    - make
    - libncurses-dev
    - flex
    - bison
    - gperf
    - doxygen
cache:
- pip
- directories:
  - tools/K210/kendryte-toolchain
  - ~/.espressif
  - tools/ESP8266/xtensa-lx106-elf
  - tools/cmake-3.14.2
before_install:
- openssl aes-256-cbc -K $encrypted_0e2adedb83b2_key -iv $encrypted_0e2adedb83b2_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- cd $TRAVIS_BUILD_DIR
# - |
#   if [ ! -d "tools/cmake-3.14.2/bin" ]; then
#     echo "Download cmake-3.14.2 ..."
#     wget https://$HOST/download/cmake-3.14.2.tar.gz
#     tar xf cmake-3.14.2.tar.gz -C tools/
#     cd tools/cmake-3.14.2
#     ./configure
#     make
#   else
#     echo "cmake-3.14.2 is already download in cache"
#   fi
- |
  if [ ! -d "tools/K210/kendryte-toolchain/bin" ]; then
    echo "Download K210 toolchain ..."
    wget https://$HOST/download/kendryte-toolchain-ubuntu-amd64-8.2.0-20190213.tar.gz
    tar zxvf kendryte-toolchain-ubuntu-amd64-8.2.0-20190213.tar.gz -C tools/K210/
  else
    echo "K210 toolchain is already download in cache"
  fi
- |
  if [ ! -d "tools/ESP8266/xtensa-lx106-elf/bin" ]; then
    echo "Download ESP8266 toolchain ..."
    wget https://$HOST/download/xtensa-lx106-elf-linux64-1.22.0-92-g8facf4c-5.2.0.tar.gz
    tar zxvf xtensa-lx106-elf-linux64-1.22.0-92-g8facf4c-5.2.0.tar.gz -C tools/ESP8266/
  else
    echo "ESP8266 toolchain is already download in cache"
  fi
- cd tools/ESP32/esp-idf
- ./install.sh
before_script:
- cd $TRAVIS_BUILD_DIR
- . add_path.sh 0
- cmake --version
script:
- cd $TRAVIS_BUILD_DIR/project/code/K210/Demo
- ./build.sh
- cd $TRAVIS_BUILD_DIR/project/code/ESP32/Demo
- idf.py build
- cd $TRAVIS_BUILD_DIR
- . add_path.sh 1
- cd $TRAVIS_BUILD_DIR/project/code/ESP8266/Demo
- make defconfig
- make -j
after_success:
- cd $TRAVIS_BUILD_DIR/docs
- doxygen
- mv html docs
- scp -o stricthostkeychecking=no -P $PORT -r docs root@$HOST:$DOCS_ROOT