# Permalinks
#
permalink:           pretty

# Setup
title:               KiteRF
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              kiterf

# Custom vars
version:             1.0.0
